version: 2
jobs:
  build:
    working_directory: ~/fn-java-fdk
    machine:
      java:
        version: oraclejdk8
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache

      - run:
          name: Build, Test and Package.
          command: mvn package

#      - store_test_results:
#          path: runtime/target/surefire-reports
#      - store_test_results:
#          path: testing/target/surefire-reports
#
#      - store_artifacts:
#          name: Upload API artefacts
#          path: api/target/
#      - store_artifacts:
#          name: Upload runtime artefacts
#          path: runtime/target/
#      - store_artifacts:
#          name: Upload testing artefacts
#          path: testing/target/
#
#      - run:
#          name: Push to maven repo
#          command: |
#            mvn -s ./settings-deploy.xml \
#                -DskipTests \
#                -DaltDeploymentRepository="bmcs-faas-snapshot-repo::default::https://swiftobjectstorage.us-phoenix-1.oraclecloud.com/v1/opc0002/mvnrepo/snapshots" \
#                -Dbmcs-faas-snapshot-repo.username="$MVN_SNAPSHOT_USER" \
#                -Dbmcs-faas-snapshot-repo.password="$MVN_SNAPSHOT_PASSWORD" \
#                deploy
#
      - run:
          name: Update go to 1.8.3
          command: ./integration-tests/install-go.sh
      - run:
         name: Update Docker to latests
         command: ./integration-tests/install-docker.sh
      - run:
          name: Install fn binary (as it is needed for the integration tests)
          command: ./integration-tests/install-fn.sh
      - run:
          name: Run integration tests
          command: COMPLETER_DOCKER_IMAGE=willprice/completer ./integration-tests/run-local.sh

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-cache
