version: 2
jobs:
  build:
    working_directory: ~/fn-java-fdk
    machine:
      java:
        version: oraclejdk8
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache

      - run:
          name: Build, Test and Package.
          command: mvn package
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          name: Upload API artefacts
          path: api/target/
      - store_artifacts:
          name: Upload runtime artefacts
          path: runtime/target/
      - store_artifacts:
          name: Upload testing artefacts
          path: testing/target/

      - run:
          name: Run integration tests
          command: ./integration-tests/run-local.sh

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-cache
