version: 2
jobs:
  build:
    working_directory: ~/fn-java-fdk
    machine:
      java:
        version: oraclejdk8
    environment:
      # store_artifacts doesn't shell substitute so the variable
      # definitions are duplicated in those steps too.
      FDK_ARTIFACT_DIR: /tmp/artifacts/fdk
      TEST_ARTIFACT_DIR: /tmp/artifacts/tests
      STAGING_DIR: /tmp/staging-repository
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache
      - run:
          name: Build
          command: mvn package
      - store_test_results:
          path: runtime/target/surefire-reports
      - store_test_results:
          path: testing/target/surefire-reports

      - run:
          name: Copy FDK artifacts to upload folder
          command: |
            mkdir -p "$FDK_ARTIFACT_DIR"
            cp -a api/target/*.jar "$FDK_ARTIFACT_DIR"
            cp -a runtime/target/*.jar "$FDK_ARTIFACT_DIR"
      - store_artifacts:
          name: Upload FDK artifacts
          path: /tmp/artifacts/fdk
      - run:
          name: Perform a local staging deploy of the maven artifacts
          command: |
            mkdir -p "$STAGING_DIR"
            mvn deploy -DskipTests -DaltDeploymentRepository=localStagingDir::default::file://"$STAGING_DIR"

      - run:
         name: Update Docker to latest
         command: ./.circleci/install-docker.sh

      - run:
         name: Login to Docker
         command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build fn-java-fdk Docker build image
          command: |
            cd build-image
            docker build -t fnproject/fn-java-fdk:build .

      - run:
          name: Build fn-java-fdk Docker runtime image
          command: |
            cd runtime
            docker build -t fnproject/fn-java-fdk .

      - run:
          name: Install fn binary (as it is needed for the integration tests)
          command: ./.circleci/install-fn.sh

      - run:
          name: Run integration tests
          command: REPOSITORY_LOCATION="$STAGING_DIR" ./integration-tests/run-local.sh
          timeout: 1200

      - run:
          name: Copy integration test results to test artifact dir
          command: |
            mkdir -p "$TEST_ARTIFACT_DIR"
            for test_dir in ./integration-tests/main/test-*; do
              test_name="$(basename "$test_dir")"
              mkdir "${TEST_ARTIFACT_DIR}/${test_name}"
              cp -a $(find "$test_dir" -maxdepth 1 -type f) "${TEST_ARTIFACT_DIR}/${test_name}"
            done
            find "${TEST_ARTIFACT_DIR}"
          when: always
      - store_artifacts:
          name: Upload integration test results to artifacts
          path: /tmp/artifacts/tests

      - deploy:
          name: Push to maven repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mvn -s ./settings-deploy.xml \
                  -DskipTests \
                  -DaltDeploymentRepository="bmcs-faas-snapshot-repo::default::https://swiftobjectstorage.us-phoenix-1.oraclecloud.com/v1/opc0002/mvnrepo/snapshots" \
                  -Dbmcs-faas-snapshot-repo.username="$MVN_SNAPSHOT_USER" \
                  -Dbmcs-faas-snapshot-repo.password="$MVN_SNAPSHOT_PASSWORD" \
                  -DdeployAtEnd=true \
                  deploy
            fi
      - deploy:
          name: Deploy fn-java-fdk Docker build image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push fnproject/fn-java-fdk:build
            fi
      - deploy:
          name: Deploy fn-java-fdk Docker runtime image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push fnproject/fn-java-fdk
            fi

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-cache
